vim.g.loaded_netrw       = 1
vim.g.loaded_netrwPlugin = 1
require('options')
require('keymaps')
require('plugins')
require('colorscheme')
require('config.lsp_config')
require('config.cmp')
require('config.lualine')
require('config.telescope')
require('config.leap')
require('config.nvim_tree')
require('config.floaterm')
require('config.comment')
require('config.indent_blankline')
require('config.fidget')
